# Generated by Django 2.2.3 on 2019-08-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_street_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_name',
        ),
    ]
