# Generated by Django 2.2.3 on 2019-08-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
